import { MonteCarlo } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Nav"

const Monte = MonteCarlo({ 
  subsets: ["latin"], 
  weight: ["400"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "React,Next,Javascript, Tailwindcss, CSS, HTML"
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
       
      <body className={`${Monte.className} text-2xl`}>
       <Navbar />
        
        {children}

      </body>
    </html>
  );
}
