import { Vujahday_Script } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Nav"
import Josh from "./components/styles.module.css"
import Footer from "./components/Footer";

const Monte =   Vujahday_Script({ 
  subsets: ["latin"], 
  weight: ["400"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "React,Next,Javascript, Tailwindcss, CSS, HTML"
};

export default function RootLayout({children}) {
  return (
    <html lang="en" className={Josh.main}>
       
      <body className={`${Monte.className} text-2xl`}>
       <Navbar />
        <div className="min-h-[80vh]">

        {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
